name: Build Debian Container Image

on:
  pull_request:
    paths:
      - "debian/**"
  push:
    paths:
      - "debian/**"
    branches:
      - master

jobs:
  docker:
    runs-on: ${{ startsWith(matrix.platforms, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: debian
          load: true
          tags: invoiceninja/invoiceninja-debian:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
