name: Build Debian Container Image

on:
  pull_request:
    paths:
      - "debian/**"
  push:
    paths:
      - "debian/**"
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug - Show current directory and files
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Files in debian directory (if exists):"
          ls -la debian/ || echo "debian directory not found"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-debian-buildx-${{ hashFiles('debian/cache_buster') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-debian-buildx-${{ hashFiles('debian/cache_buster') }}-

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: debian  
          file: debian/Dockerfile  
          load: true
          tags: invoiceninja/invoiceninja-debian:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache